### PR TITLE
Adding optional EnvironmentFile

### PR DESCRIPTION
**Pull request by balki**
Reference:
https://caddyserver.com/docs/caddyfile/concepts#environment-variables
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=

### CODE REVIEW

**Comment by ashpieboop** [comment]
Thanks a lot for this amazing pull request! I will merge this asap.

**Review by ashpieboop — APPROVED** [review]

**Comment by ashpieboop** [comment]
Actually isn't `envfile` a bit redundant for a *file* name? I would suggest the more simple `/etc/caddy/env` (please lmk if you see any objection).

**Comment by balki** [comment]
> Actually isn't `envfile` a bit redundant for a _file_ name? I would suggest the more simple `/etc/caddy/env` (please lmk if you see any objection).

Caddy 1.0 automatically read the file named envfile (at least it did in my setup). Either name is fine with me. :)

**Comment by ashpieboop** [comment]
I don't want to impose my personal opinions on this so let's stick to the traditional `envfile`. Thanks again!

**Pull request merged**
